//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace AutoPBR.App.Lang;

using System.Globalization;
using System.Resources;

/// <summary>Strongly-typed access to Lang resources. Set Culture to switch language at runtime.</summary>
public static class Resources
{
    private static ResourceManager? _resourceMan;
    private static CultureInfo? _resourceCulture;

    public static CultureInfo? Culture
    {
        get => _resourceCulture;
        set => _resourceCulture = value;
    }

    public static string ColorScheme => GetString("ColorScheme");
    public static string ColorSchemeDark => GetString("ColorSchemeDark");
    public static string ColorSchemeBlue => GetString("ColorSchemeBlue");
    public static string ColorSchemeGreen => GetString("ColorSchemeGreen");
    public static string ColorSchemePurple => GetString("ColorSchemePurple");
    public static string ColorSchemeAmber => GetString("ColorSchemeAmber");
    public static string ColorSchemeTeal => GetString("ColorSchemeTeal");
    public static string ColorSchemeRose => GetString("ColorSchemeRose");
    public static string ColorSchemeMono => GetString("ColorSchemeMono");
    public static string ColorSchemeOcean => GetString("ColorSchemeOcean");
    public static string ColorSchemeSunset => GetString("ColorSchemeSunset");
    public static string Language => GetString("Language");
    public static string Appearance => GetString("Appearance");
    public static string UiScaling => GetString("UiScaling");
    public static string UiScalingTooltip => GetString("UiScalingTooltip");
    public static string AppTitle => GetString("AppTitle");
    public static string AppSubtitle => GetString("AppSubtitle");
    public static string TabConvert => GetString("TabConvert");
    public static string TabScan => GetString("TabScan");
    public static string TabExplore => GetString("TabExplore");
    public static string ScanButton => GetString("ScanButton");
    public static string BatchConversion => GetString("BatchConversion");
    public static string BatchConversionDescription => GetString("BatchConversionDescription");
    public static string BatchFolderWatermark => GetString("BatchFolderWatermark");
    public static string BrowseBatchFolder => GetString("BrowseBatchFolder");
    public static string ScanBatchButton => GetString("ScanBatchButton");
    public static string BatchConvertButton => GetString("BatchConvertButton");
    public static string ExploreArchiveContents => GetString("ExploreArchiveContents");
    public static string ResourceExplorer => GetString("ResourceExplorer");
    public static string ExploreEmptyMessage => GetString("ExploreEmptyMessage");
    public static string ExploreExpandAll => GetString("ExploreExpandAll");
    public static string ExploreCollapseAll => GetString("ExploreCollapseAll");
    public static string ClearTagOverrides => GetString("ClearTagOverrides");
    public static string ClearTagOverridesTooltip => GetString("ClearTagOverridesTooltip");
    public static string TagMenuDontApply => GetString("TagMenuDontApply");
    public static string TagMenuApply => GetString("TagMenuApply");
    public static string TagRules => GetString("TagRules");
    public static string TagRulesCustomDescription => GetString("TagRulesCustomDescription");
    public static string TagRuleId => GetString("TagRuleId");
    public static string TagRuleDisplayName => GetString("TagRuleDisplayName");
    public static string TagRuleKeywords => GetString("TagRuleKeywords");
    public static string TagRuleSemanticHints => GetString("TagRuleSemanticHints");
    public static string MaterialTagSemanticMl => GetString("MaterialTagSemanticMl");
    public static string MaterialTagSemanticMlDescription => GetString("MaterialTagSemanticMlDescription");
    public static string MaterialTagMinSimilarity => GetString("MaterialTagMinSimilarity");
    public static string MaterialTagMaxCount => GetString("MaterialTagMaxCount");
    public static string MaterialTagMaxCountTooltip => GetString("MaterialTagMaxCountTooltip");
    public static string MaterialTagCertaintyThreshold => GetString("MaterialTagCertaintyThreshold");
    public static string MaterialTagCertaintyThresholdTooltip => GetString("MaterialTagCertaintyThresholdTooltip");
    public static string DictionaryEvidenceEnabled => GetString("DictionaryEvidenceEnabled");
    public static string DictionaryEvidenceWeight => GetString("DictionaryEvidenceWeight");
    public static string DictionaryMinEvidenceScore => GetString("DictionaryMinEvidenceScore");
    public static string DictionaryRequestTimeoutMs => GetString("DictionaryRequestTimeoutMs");
    public static string TagLegendMaterials => GetString("TagLegendMaterials");
    public static string TagLegendFlags => GetString("TagLegendFlags");
    public static string ExploreColumnResource => GetString("ExploreColumnResource");
    public static string TagRuleKindLabel => GetString("TagRuleKindLabel");
    public static string UseSemanticMaterialTags => GetString("UseSemanticMaterialTags");
    public static string AddCustomTagRule => GetString("AddCustomTagRule");
    public static string RemoveTagRule => GetString("RemoveTagRule");
    public static string RefreshTagRules => GetString("RefreshTagRules");
    public static string InvertHeight => GetString("InvertHeight");
    public static string InvertSpecular => GetString("InvertSpecular");
    public static string TagRuleNormalIntensityOpt => GetString("TagRuleNormalIntensityOpt");
    public static string TagRuleHeightIntensityOpt => GetString("TagRuleHeightIntensityOpt");
    public static string TagRuleIntensityTooltip => GetString("TagRuleIntensityTooltip");
    public static string TagRuleInvertNormalX => GetString("TagRuleInvertNormalX");
    public static string TagRuleInvertNormalY => GetString("TagRuleInvertNormalY");
    public static string TagRuleEnabled => GetString("TagRuleEnabled");
    public static string TagRuleEnabledTooltip => GetString("TagRuleEnabledTooltip");
    public static string TagRuleMoveUp => GetString("TagRuleMoveUp");
    public static string TagRuleMoveDown => GetString("TagRuleMoveDown");
    public static string TagRuleMoveUpTooltip => GetString("TagRuleMoveUpTooltip");
    public static string TagRuleMoveDownTooltip => GetString("TagRuleMoveDownTooltip");
    public static string ExportTagRules => GetString("ExportTagRules");
    public static string ImportTagRules => GetString("ImportTagRules");
    public static string ExportTagRulesTooltip => GetString("ExportTagRulesTooltip");
    public static string ImportTagRulesTooltip => GetString("ImportTagRulesTooltip");
    public static string RefreshTagRulesTooltip => GetString("RefreshTagRulesTooltip");
    public static string Log_TagRulesExported => GetString("Log_TagRulesExported");
    public static string Log_TagRulesImported => GetString("Log_TagRulesImported");
    public static string Log_TagRulesImportFailed => GetString("Log_TagRulesImportFailed");
    public static string ExploreBack => GetString("ExploreBack");
    public static string ExploreFocusAssets => GetString("ExploreFocusAssets");
    public static string TabNormals => GetString("TabNormals");
    public static string TabSettings => GetString("TabSettings");
    public static string Input => GetString("Input");
    public static string InputSourceModeTooltip => GetString("InputSourceModeTooltip");
    public static string ResourcePackWatermark => GetString("ResourcePackWatermark");
    public static string Browse => GetString("Browse");
    public static string Log => GetString("Log");
    public static string OpenLogFolder => GetString("OpenLogFolder");
    public static string GenerationSettings => GetString("GenerationSettings");
    public static string TuneNormals => GetString("TuneNormals");
    public static string TuneSpecular => GetString("TuneSpecular");
    public static string NormalsTuning => GetString("NormalsTuning");
    public static string SpecularTuning => GetString("SpecularTuning");
    public static string AiTuning => GetString("AiTuning");
    public static string TuneHeight => GetString("TuneHeight");
    public static string HeightmapTuning => GetString("HeightmapTuning");
    public static string NormalStrength => GetString("NormalStrength");
    public static string NormalStrengthTooltip => GetString("NormalStrengthTooltip");
    public static string HeightStrength => GetString("HeightStrength");
    public static string HeightStrengthTooltip => GetString("HeightStrengthTooltip");
    public static string BrickProbeTuning => GetString("BrickProbeTuning");
    public static string BrickProbeEnable => GetString("BrickProbeEnable");
    public static string BrickProbeMinStructure => GetString("BrickProbeMinStructure");
    public static string BrickProbeInvertDelta => GetString("BrickProbeInvertDelta");
    public static string BrickProbeLightGroutDelta => GetString("BrickProbeLightGroutDelta");
    public static string BrickProbeEnableTooltip => GetString("BrickProbeEnableTooltip");
    public static string BrickProbeMinStructureTooltip => GetString("BrickProbeMinStructureTooltip");
    public static string BrickProbeInvertDeltaTooltip => GetString("BrickProbeInvertDeltaTooltip");
    public static string BrickProbeLightGroutDeltaTooltip => GetString("BrickProbeLightGroutDeltaTooltip");
    public static string PreviewBrickProbeDebug => GetString("PreviewBrickProbeDebug");
    public static string PreviewBrickProbeDebugTooltip => GetString("PreviewBrickProbeDebugTooltip");
    public static string NormalOperatorLabel => GetString("NormalOperatorLabel");
    public static string NormalKernelSizeLabel => GetString("NormalKernelSizeLabel");
    public static string Derivative => GetString("Derivative");
    public static string SmoothnessScale => GetString("SmoothnessScale");
    public static string SmoothnessScaleTooltip => GetString("SmoothnessScaleTooltip");
    public static string MetallicBoost => GetString("MetallicBoost");
    public static string MetallicBoostTooltip => GetString("MetallicBoostTooltip");
    public static string PorosityBias => GetString("PorosityBias");
    public static string PorosityBiasTooltip => GetString("PorosityBiasTooltip");
    public static string PlantMaterialPorosityExtra => GetString("PlantMaterialPorosityExtra");
    public static string PlantMaterialPorosityExtraTooltip => GetString("PlantMaterialPorosityExtraTooltip");
    public static string MlSpecularHeuristicBlend => GetString("MlSpecularHeuristicBlend");
    public static string MlSpecularHeuristicBlendTooltip => GetString("MlSpecularHeuristicBlendTooltip");
    public static string MlSpecularBlendMode => GetString("MlSpecularBlendMode");
    public static string MlSpecularBlendModeTooltip => GetString("MlSpecularBlendModeTooltip");
    public static string MlSpecularBlendMath => GetString("MlSpecularBlendMath");
    public static string MlSpecularBlendMathTooltip => GetString("MlSpecularBlendMathTooltip");
    public static string MlSpecularBlendMathLinear => GetString("MlSpecularBlendMathLinear");
    public static string MlSpecularBlendMathSoftLight => GetString("MlSpecularBlendMathSoftLight");
    public static string MlSpecularBlendMathOverlay => GetString("MlSpecularBlendMathOverlay");
    public static string MlSpecularBlendMathScreen => GetString("MlSpecularBlendMathScreen");
    public static string MlSpecularBlendMathBiasGain => GetString("MlSpecularBlendMathBiasGain");
    public static string MlSpecularBlendMathSigmoidCrossfade => GetString("MlSpecularBlendMathSigmoidCrossfade");
    public static string MlSpecularBlendModeSmoothnessOnly => GetString("MlSpecularBlendModeSmoothnessOnly");
    public static string MlSpecularBlendModeFull => GetString("MlSpecularBlendModeFull");
    public static string MlSpecularBlendModeAiMetalAndEmissive => GetString("MlSpecularBlendModeAiMetalAndEmissive");
    public static string FastSpecular => GetString("FastSpecular");
    public static string FastSpecularTooltip => GetString("FastSpecularTooltip");
    public static string Foliage => GetString("Foliage");
    public static string FoliageTooltip => GetString("FoliageTooltip");
    public static string IgnoreAll => GetString("IgnoreAll");
    public static string NoHeight => GetString("NoHeight");
    public static string ConvertAll => GetString("ConvertAll");
    public static string HeightFromNormals => GetString("HeightFromNormals");
    public static string HeightFromNormalsTooltip => GetString("HeightFromNormalsTooltip");
    public static string NormalsFromDeepBump => GetString("NormalsFromDeepBump");
    public static string NormalsFromDeepBumpTooltip => GetString("NormalsFromDeepBumpTooltip");
    public static string DeepBumpOverlap => GetString("DeepBumpOverlap");
    public static string DeepBumpOverlapTooltip => GetString("DeepBumpOverlapTooltip");
    public static string DeepBumpOverlapSmall => GetString("DeepBumpOverlapSmall");
    public static string DeepBumpOverlapMedium => GetString("DeepBumpOverlapMedium");
    public static string DeepBumpOverlapLarge => GetString("DeepBumpOverlapLarge");
    public static string DeepBumpAdvanced => GetString("DeepBumpAdvanced");
    public static string DeepBumpInputMode => GetString("DeepBumpInputMode");
    public static string DeepBumpInputModeAuto => GetString("DeepBumpInputModeAuto");
    public static string DeepBumpInputModeGrayscale => GetString("DeepBumpInputModeGrayscale");
    public static string DeepBumpInputModeRgb => GetString("DeepBumpInputModeRgb");
    public static string DeepBumpForceBlue255 => GetString("DeepBumpForceBlue255");
    public static string DeepBumpNormalIntensity => GetString("DeepBumpNormalIntensity");
    public static string DeepBumpNormalIntensityTooltip => GetString("DeepBumpNormalIntensityTooltip");
    public static string DeepBumpNormalSoftClamp => GetString("DeepBumpNormalSoftClamp");
    public static string DeepBumpNormalSoftClampTooltip => GetString("DeepBumpNormalSoftClampTooltip");
    public static string DeepBumpEdgeGuidedEnhance => GetString("DeepBumpEdgeGuidedEnhance");
    public static string DeepBumpEdgeGuidedStrength => GetString("DeepBumpEdgeGuidedStrength");
    public static string DeepBumpEdgeGuidedStrengthTooltip => GetString("DeepBumpEdgeGuidedStrengthTooltip");
    public static string DeepBumpEdgeGuidedGamma => GetString("DeepBumpEdgeGuidedGamma");
    public static string DeepBumpEdgeGuidedGammaTooltip => GetString("DeepBumpEdgeGuidedGammaTooltip");
    public static string DeepBumpEdgeGuidedDirectionMix => GetString("DeepBumpEdgeGuidedDirectionMix");
    public static string DeepBumpEdgeGuidedDirectionMixTooltip => GetString("DeepBumpEdgeGuidedDirectionMixTooltip");
    public static string NormalHeightTransparentAlphaClampMax => GetString("NormalHeightTransparentAlphaClampMax");
    public static string NormalHeightTransparentAlphaClampMaxTooltip => GetString("NormalHeightTransparentAlphaClampMaxTooltip");

    public static string Advanced => GetString("Advanced");
    public static string Preprocessing => GetString("Preprocessing");
    public static string PreprocessLinearize => GetString("PreprocessLinearize");
    public static string PreprocessDenoiseRadius => GetString("PreprocessDenoiseRadius");
    public static string PreprocessDenoiseBlend => GetString("PreprocessDenoiseBlend");
    public static string PreprocessFrequencySplit => GetString("PreprocessFrequencySplit");
    public static string PreprocessFrequencyRadius => GetString("PreprocessFrequencyRadius");
    public static string PreprocessFrequencyDetailStrength => GetString("PreprocessFrequencyDetailStrength");

    public static string SpecularAdvanced => GetString("SpecularAdvanced");
    public static string SpecularPercentileRemap => GetString("SpecularPercentileRemap");
    public static string SpecularRemapLowPercentile => GetString("SpecularRemapLowPercentile");
    public static string SpecularRemapHighPercentile => GetString("SpecularRemapHighPercentile");
    public static string UseMlSpecularPredictor => GetString("UseMlSpecularPredictor");
    public static string UseMlSpecularPredictorTooltip => GetString("UseMlSpecularPredictorTooltip");
    public static string MlSpecularModelPath => GetString("MlSpecularModelPath");
    public static string MlSpecularModelPathWatermark => GetString("MlSpecularModelPathWatermark");
    public static string MlSpecularPerResolutionHeader => GetString("MlSpecularPerResolutionHeader");
    public static string MlSpecularPerResolutionTooltip => GetString("MlSpecularPerResolutionTooltip");
    public static string MlSpecularUseEdgeChannel => GetString("MlSpecularUseEdgeChannel");
    public static string MlSpecularTransparentAlphaClampMax => GetString("MlSpecularTransparentAlphaClampMax");
    public static string MlSpecularTransparentAlphaClampMaxTooltip => GetString("MlSpecularTransparentAlphaClampMaxTooltip");
    public static string SpecularDebugSection => GetString("SpecularDebugSection");
    public static string SpecularDebugDisableHeuristicSpecular => GetString("SpecularDebugDisableHeuristicSpecular");
    public static string SpecularDebugDisableHeuristicSpecularTooltip => GetString("SpecularDebugDisableHeuristicSpecularTooltip");
    public static string SpecularDebugSkipSpecularRemap => GetString("SpecularDebugSkipSpecularRemap");
    public static string SpecularDebugSkipSpecularRemapTooltip => GetString("SpecularDebugSkipSpecularRemapTooltip");
    public static string SpecularDebugVerboseSpecularMl => GetString("SpecularDebugVerboseSpecularMl");
    public static string SpecularDebugVerboseSpecularMlTooltip => GetString("SpecularDebugVerboseSpecularMlTooltip");

    public static string AoAdvanced => GetString("AoAdvanced");
    public static string GenerateAo => GetString("GenerateAo");
    public static string AoRadius => GetString("AoRadius");
    public static string AoStrength => GetString("AoStrength");
    public static string TextureTypes => GetString("TextureTypes");
    public static string Blocks => GetString("Blocks");
    public static string BlocksTooltip => GetString("BlocksTooltip");
    public static string Items => GetString("Items");
    public static string ItemsTooltip => GetString("ItemsTooltip");
    public static string Armor => GetString("Armor");
    public static string ArmorTooltip => GetString("ArmorTooltip");
    public static string Entity => GetString("Entity");
    public static string EntityTooltip => GetString("EntityTooltip");
    public static string Particles => GetString("Particles");
    public static string ParticlesTooltip => GetString("ParticlesTooltip");
    public static string FilterWatermark => GetString("FilterWatermark");
    public static string ExploreTagFilter => GetString("ExploreTagFilter");
    public static string ExploreTagFilterAll => GetString("ExploreTagFilterAll");
    public static string Output => GetString("Output");
    public static string OutputFolderWatermark => GetString("OutputFolderWatermark");
    public static string OutputPathWatermark => GetString("OutputPathWatermark");
    public static string Engine => GetString("Engine");
    public static string MaxThreads => GetString("MaxThreads");
    public static string MaxThreadsTooltip => GetString("MaxThreadsTooltip");
    public static string OnnxPreferTensorRt => GetString("OnnxPreferTensorRt");
    public static string OnnxPreferTensorRtTooltip => GetString("OnnxPreferTensorRtTooltip");
    public static string TempFolder => GetString("TempFolder");
    public static string TempFolderTooltip => GetString("TempFolderTooltip");
    public static string TempFolderWatermark => GetString("TempFolderWatermark");
    public static string CustomThreadedExtraction => GetString("CustomThreadedExtraction");
    public static string CustomThreadedExtractionTooltip => GetString("CustomThreadedExtractionTooltip");
    public static string UseLegacyExtractor => GetString("UseLegacyExtractor");
    public static string UseLegacyExtractorTooltip => GetString("UseLegacyExtractorTooltip");
    public static string Cancel => GetString("Cancel");
    public static string Convert => GetString("Convert");
    public static string UIThemeTooltip => GetString("UIThemeTooltip");
    public static string UILanguageTooltip => GetString("UILanguageTooltip");
    public static string BackgroundTaskMaterialTags => GetString("BackgroundTaskMaterialTags");
    public static string BackgroundTaskExploreCache => GetString("BackgroundTaskExploreCache");
    public static string BackgroundTasksHeader => GetString("BackgroundTasksHeader");

    public static string GetStatusString(string key, params object[] args)
    {
        var s = GetString(key);
        return args.Length > 0 ? string.Format(s, args) : s;
    }

    public static string GetString(string key)
    {
        var rm = ResourceManager;
        var c = _resourceCulture;
        return rm?.GetString(key, c) ?? key;
    }

    private static ResourceManager ResourceManager
    {
        get
        {
            if (_resourceMan is null)
            {
                var t = typeof(Resources);
                _resourceMan = new ResourceManager("AutoPBR.App.Lang.Resources", t.Assembly);
            }
            return _resourceMan;
        }
    }
}
