using System.Globalization;
using System.Text;
using System.Text.Json.Nodes;

namespace AutoPBR.Tools.GeometryCompiler;

/// <summary>
/// Emits C# <c>EntityCuboid</c> span tables from validated geometry IR shards (build-time codegen pilot).
/// </summary>
internal static class GeometryIrCodegenHost
{
    private static readonly string[] PilotJvmNames =
    [
        "net.minecraft.client.model.animal.fish.CodModel",
        "net.minecraft.client.model.animal.fish.SalmonModel",
        "net.minecraft.client.model.animal.chicken.ChickenModel"
    ];

    public static int RunCodegenEntityCuboids(string[] args)
    {
        var root = Program.FindRepoRoot();
        var version = args.FirstOrDefault(a => !a.StartsWith('-')) ?? "26.1.2";
        var outDir = Path.Combine(root, "src", "AutoPBR.Core", "Preview", "Generated");
        Directory.CreateDirectory(outDir);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("namespace AutoPBR.Core.Preview.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static partial class GeometryIrEntityCuboidTables");
        sb.AppendLine("{");

        var wrote = 0;
        foreach (var jvm in PilotJvmNames)
        {
            var shardPath = Path.Combine(root, "docs", "generated", "geometry", version, $"{jvm}.json");
            if (!File.Exists(shardPath))
            {
                continue;
            }

            var validation = GeometryIrStructuralValidator.ValidateFile(shardPath,
                new GeometryIrStructuralValidator.Options(Strict: true, RequireOkStatus: true));
            if (!validation.IsValid)
            {
                Console.Error.WriteLine($"Skip codegen {jvm}: strict validation failed");
                continue;
            }

            var node = JsonNode.Parse(File.ReadAllText(shardPath))!.AsObject();
            if (node["roots"] is not JsonArray roots)
            {
                continue;
            }

            var typeName = jvm.Split('.')[^1];
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"    private static readonly EntityModelRuntime.EntityCuboid[] {typeName}BodyLayerData =");
            sb.AppendLine("    [");
            EmitCuboidsFromParts(roots, sb, "        ");
            sb.AppendLine("    ];");
            sb.AppendLine();
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"    internal static ReadOnlySpan<EntityModelRuntime.EntityCuboid> {typeName}BodyLayer => {typeName}BodyLayerData;");
            sb.AppendLine();
            wrote++;
        }

        sb.AppendLine("}");

        var outPath = Path.Combine(outDir, "GeometryIrEntityCuboidTables.g.cs");
        File.WriteAllText(outPath, sb.ToString());
        Console.WriteLine($"Wrote {outPath} ({wrote} models)");
        return wrote > 0 ? 0 : 1;
    }

    private static void EmitCuboidsFromParts(JsonArray parts, StringBuilder sb, string indent)
    {
        foreach (var partNode in parts)
        {
            if (partNode is not JsonObject part)
            {
                continue;
            }

            if (part["cuboids"] is JsonArray cuboids)
            {
                foreach (var c in cuboids)
                {
                    if (c is not JsonObject co ||
                        co["from"] is not JsonArray from || from.Count < 3 ||
                        co["to"] is not JsonArray to || to.Count < 3 ||
                        co["uvOrigin"] is not JsonArray uv || uv.Count < 2)
                    {
                        continue;
                    }

                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"{indent}new EntityModelRuntime.EntityCuboid({Fmt(from[0])}f, {Fmt(from[1])}f, {Fmt(from[2])}f, {Fmt(to[0])}f, {Fmt(to[1])}f, {Fmt(to[2])}f, {uv[0]}, {uv[1]}),");
                }
            }

            if (part["children"] is JsonArray children)
            {
                EmitCuboidsFromParts(children, sb, indent);
            }
        }
    }

    private static string Fmt(JsonNode? n) =>
        n is null ? "0" : n.GetValue<double>().ToString("G9", CultureInfo.InvariantCulture);
}
