using System.Text.Json;
using AutoPBR.Core.Models;

namespace AutoPBR.Core;

/// <summary>
/// Writes pack metadata and creates the output packed zip with converted textures.
/// </summary>
internal static class PackWriter
{
    private static readonly JsonSerializerOptions WriteIndentedJsonOptions = new() { WriteIndented = true };

    public static void WritePackMetadata(string extracted)
    {
        var path = Path.Combine(extracted, "pack.mcmeta");
        var packFormat = 22; // default for recent versions
        if (File.Exists(path))
        {
            try
            {
                var json = File.ReadAllText(path);
                using var doc = JsonDocument.Parse(json);
                if (doc.RootElement.TryGetProperty("pack", out var pack) &&
                    pack.TryGetProperty("pack_format", out var pf))
                {
                    packFormat = pf.GetInt32();
                }
            }
            catch
            {
                /* keep default */
            }
        }

        var mcmeta = new Dictionary<string, object>
        {
            ["pack"] = new Dictionary<string, object>
            {
                ["pack_format"] = packFormat,
                ["description"] = "Generated by AutoPBR"
            }
        };
        File.WriteAllText(path, JsonSerializer.Serialize(mcmeta, WriteIndentedJsonOptions));
    }

    public static void CreateOutputZip(
        string extracted,
        string outputZipPath,
        IReadOnlyList<TextureWorkItem> textures,
        AutoPbrOptions options,
        IProgress<ConversionProgress>? progress,
        CancellationToken cancellationToken)
    {
        ThreadingUtil.SetThreadName("AutoPBR.PackMain");
        var files = new List<string>();

        var packPng = Path.Combine(extracted, "pack.png");
        if (File.Exists(packPng))
        {
            files.Add(packPng);
        }

        var packMcmeta = Path.Combine(extracted, "pack.mcmeta");
        files.Add(packMcmeta);
        var licensePath = Path.Combine(extracted, "LICENSE");
        if (File.Exists(licensePath))
        {
            files.Add(licensePath);
        }
        else
        {
            var licenseLower = Path.Combine(extracted, "license");
            if (File.Exists(licenseLower))
            {
                files.Add(licenseLower);
            }
        }

        foreach (var t in textures)
        {
            if (!t.SpecularOnly && File.Exists(t.NormalPath))
            {
                files.Add(t.NormalPath);
            }

            if (File.Exists(t.SpecularPath))
            {
                files.Add(t.SpecularPath);
            }
        }

        ParallelZipWriter.WriteZip(outputZipPath, files, extracted, options, progress, ConversionStage.Packing,
            cancellationToken);
    }
}

